on:
  push:
    branches:
    - main

 

permissions:
      id-token: write
      contents: read

 

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

 

 

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBS_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
